import {
  Briefcase,
  Calendar,
  Cpu,
  DollarSign,
  Edit,
  FileText,
  HardDrive,
  Rss,
  Settings,
  ShoppingCart,
  Truck,
  User,
  Zap,
  Phone,
  FileCog,
  Shield,
  Anchor,
  BarChart,
  Box,
  Code,
  GitBranch,
  Link,
  Monitor,
  Scissors,
  Cloud,
  Database,
  FilePlus,
  MapPin,
  Search,
  ShieldCheck
} from 'lucide-react';
import { JSX } from 'react';

// Define your icon mapping
export const fieldDetailIcons: Record<string, JSX.Element> = {
  'Nhân viên chăm sóc da': <User />,
  'Phát triển khách hàng garage': <Truck />,
  'Điều hành tour du lịch': <Calendar />,
  'Nhân viên xử lý khiếu nại': <FileText />,
  'Nhân viên kiểm kê hàng hóa': <ShoppingCart />,
  'Nhân viên quản lý quỹ': <DollarSign />,
  'Phát triển ứng dụng iOS': <Cpu />,
  'Chuyên viên phân tích thị trường R&D': <Briefcase />,
  'Bếp trưởng nhà hàng': <User />,
  'Tư vấn gói tập gym': <User />,
  'Dược sĩ lâm sàng': <User />,
  'Nhân viên bảo trì máy móc': <Cpu />,
  'Nghiên cứu nông nghiệp': <Briefcase />,
  'Dược sĩ bán lẻ': <ShoppingCart />,
  'Đào tạo giáo viên': <User />,
  'Quản lý dự án biên phiên dịch': <Briefcase />,
  'Chuyên viên quan hệ khách hàng': <User />,
  'Tài xế xe tải': <Truck />,
  'Nhân viên bán hàng thời trang': <ShoppingCart />,
  'Quản lý sản phẩm TMĐT': <Briefcase />,
  'Nhân viên chế biến thực phẩm': <ShoppingCart />,
  'Telesales sản phẩm ngân hàng': <FileText />,
  'Thiết kế kết cấu xây dựng': <FileText />,
  'Nhân viên kế toán thuế': <DollarSign />,
  'Nhân viên bảo trì hệ thống điện': <Cpu />,
  'Nhân viên nhập liệu': <FileText />,
  'Chuyên viên tư vấn làm đẹp': <User />,
  'Nhân viên kinh doanh': <Briefcase />,
  'Nhân viên bán lẻ': <ShoppingCart />,
  'Tư vấn bán hàng nhôm': <Briefcase />,
  'Phát triển phần mềm AI': <Cpu />,
  'Tư vấn tài chính': <DollarSign />,
  'Huấn luyện viên thể hình': <User />,
  'Nhân viên xuất nhập khẩu': <Truck />,
  'Quản lý kinh doanh khu vực': <Briefcase />,
  'Kỹ sư cơ khí': <Cpu />,
  'Kế toán trưởng': <DollarSign />,
  'Quản lý nội dung số': <FileText />,
  'Quản lý chi nhánh ngân hàng': <Briefcase />,
  'Hướng dẫn viên du lịch': <Calendar />,
  'Chuyên viên phân tích tài chính': <DollarSign />,
  'Chuyên viên tuyển dụng': <User />,
  'Biên dịch viên': <FileText />,
  'Quản lý phòng khám': <User />,
  'Nhân viên tư vấn giáo dục': <User />,
  'Họa sĩ minh họa': <User />,
  'Nhân viên lễ tân': <User />,
  'Bán hàng thời trang': <ShoppingCart />,
  'Quản lý nhà hàng': <User />,
  'Nhân viên kinh doanh bất động sản': <Briefcase />,
  'Quản lý đội chăm sóc khách hàng': <User />,
  'Chuyên viên marketing số': <Edit />,
  'Kỹ thuật viên sửa chữa điện lạnh': <Settings />,
  'Quản lý nội dung mạng xã hội': <Rss />,
  'Chuyên viên hỗ trợ qua điện thoại': <Phone />,
  'Phát triển thiết bị y tế': <HardDrive />,
  'Kỹ thuật viên công nghệ sinh học': <Cpu />,
  'Nhân viên tư vấn tài chính': <DollarSign />,
  'Nhân viên thu mua': <ShoppingCart />,
  'Kỹ thuật viên viễn thông': <Zap />,
  'Quản lý thương hiệu': <Briefcase />,
  'Nhân viên thiết kế in ấn': <Edit />,
  'Quản lý dự án bất động sản': <Briefcase />,
  'Nhân viên xử lý bồi thường': <FileText />,
  'Nhân viên chứng từ xuất nhập khẩu': <Phone />,
  'Chuyên viên kiểm thử phần mềm (QA)': <HardDrive />,
  'Chuyên viên tư vấn doanh nghiệp': <Briefcase />,
  'Thiết kế mẫu thời trang dệt may': <Edit />,
  'Chuyên viên kiểm định chất lượng dược': <FileText />,
  'Quản lý cửa hàng': <ShoppingCart />,
  'Quản lý đội bảo trì điện lạnh': <Settings />,
  'Thiết kế mạch điện tử': <Cpu />,
  'Giáo viên mầm non': <User />,
  'Thư ký giám đốc': <FileText />,
  'Nghiên cứu viên R&D': <Briefcase />,
  'Nhân viên bưu chính': <Truck />,
  'Tuyển dụng nhân viên miền Bắc': <User />,
  'Chuyên viên vật lý trị liệu thể thao': <User />,
  'Thiết kế nội thất': <Edit />,
  'Điều phối viên dự án': <Calendar />,
  'Quản lý cửa hàng thời trang': <ShoppingCart />,
  'Quản lý dự án IT': <Cpu />,
  'Tổ chức sự kiện': <Calendar />,
  'Thiết kế sản phẩm': <Edit />,
  'Hỗ trợ kỹ thuật': <Settings />,
  'Chuyên viên PR': <User />,
  'Quản lý dự án xây dựng': <FileText />,
  'Biên tập viên xuất bản': <FileText />,
  'Nhân viên tư vấn dược phẩm': <ShoppingCart />,
  'Chuyên viên định giá bất động sản': <DollarSign />,
  'Kỹ sư viễn thông': <Zap />,
  'Nhân viên chăm sóc khách hàng online': <User />,
  'Chiến lược kinh doanh quảng cáo': <Edit />,
  'Thiết kế bản vẽ cơ khí': <Cpu />,
  'Quản lý dự án công nghệ': <Cpu />,
  'Nhân viên hành chính nhân sự': <User />,
  'Nhân viên hỗ trợ hành chính': <User />,
  'Kỹ thuật viên bảo trì': <Settings />,
  'Quản lý sản xuất': <Briefcase />,
  'Thợ sửa chữa ô tô': <Settings />,
  'Bác sĩ phẫu thuật': <User />,
  'Quản lý sàn thương mại điện tử': <ShoppingCart />,
  'Chuyên viên lập kế hoạch dự án': <FileCog />,
  'Quản lý truyền thông': <Rss />,
  'Kỹ thuật viên phần cứng': <Cpu />,
  'Nhân viên kế toán tổng hợp': <DollarSign />,
  'Tư vấn bán hàng online': <ShoppingCart />,
  'Kỹ sư phát triển sản phẩm': <Cpu />,
  'Nhân viên giao hàng': <Truck />,
  'Lập trình viên Fintech': <Cpu />,
  'Quản lý trung tâm thể thao': <User />,
  'Trợ lý dự án': <FileText />,
  'Nhân viên hành chính': <User />,
  'Quản lý trung tâm đào tạo': <Briefcase />,
  'Quản lý phòng thí nghiệm': <FileText />,
  'Nhân viên kinh doanh F&B': <ShoppingCart />,
  'Bán hàng tiêu dùng': <ShoppingCart />,
  'Quản lý truyền thông thương hiệu': <Rss />,
  'Nghiên cứu viên dược phẩm': <Briefcase />,
  'Quản lý dự án thiết kế': <Briefcase />,
  'Chuyên viên tín dụng': <DollarSign />,
  'Kiểm tra chất lượng': <FileCog />,
  'Quản lý dây chuyền sản xuất dệt': <Briefcase />,
  'Chuyên viên nội dung (content marketing)': <Edit />,
  'Quản lý mạng lưới bưu chính': <Truck />,
  'Nhân viên thu ngân': <ShoppingCart />,
  'Chuyên viên đào tạo và phát triển': <User />,
  'Quản lý xuất nhập khẩu': <Truck />,
  'Nhân viên lập kế hoạch kinh doanh': <DollarSign />,
  'Chuyên viên chăm sóc khách hàng viễn thông': <User />,
  'Tuyển dụng nhân sự': <User />,
  'Quản lý đội bảo trì': <Settings />,
  'Thợ gia công cơ khí': <Cpu />,
  'Nhân viên tư vấn bảo hiểm': <DollarSign />,
  'Chuyên viên tư vấn chiến lược': <Briefcase />,
  'Quản lý kho': <Briefcase />,
  'Điều hành khách sạn': <User />,
  'Chuyên viên marketing thời trang': <Edit />,
  'Thiết kế thời trang': <Edit />,
  'Nhân viên dịch thuật tài liệu': <FileText />,
  'Quản lý công trường': <FileText />,
  'Kỹ sư DevOps': <Cpu />,
  'Chuyên viên trưng bày sản phẩm': <Edit />,
  'Bác sĩ đa khoa': <User />,
  'Tư vấn giải pháp bảo hiểm': <DollarSign />,
  'Quản lý kinh doanh sản phẩm kỹ thuật': <Cpu />,
  'Đào tạo nội bộ': <User />,
  'Nhân viên môi giới': <Briefcase />,
  'Dịch vụ bảo vệ': <Shield />,
  'Chuyên viên kiểm soát nội bộ': <FileCog />,
  'Quản lý vận tải biển': <Anchor />,
  'Hỗ trợ khách hàng': <User />,
  'Chuyên viên kiểm soát chất lượng thực phẩm': <BarChart />,
  'Phát triển nội dung giáo dục': <Edit />,
  'Quản lý đội xe vận tải': <Truck />,
  'Quản lý quảng cáo mạng xã hội': <Rss />,
  'Bán hàng thực phẩm': <ShoppingCart />,
  'Điều dưỡng viên': <User />,
  'Quản lý phòng giao dịch tài chính': <DollarSign />,
  'Phóng viên': <FileText />,
  'Quản lý sản xuất dược phẩm': <Briefcase />,
  'Kiến trúc sư': <Monitor />,
  'Quản lý dây chuyền sản xuất ô tô': <Monitor />,
  'Tư vấn bán hàng': <ShoppingCart />,
  'Thợ may công nghiệp': <Scissors />,
  'Kỹ thuật viên xét nghiệm': <HardDrive />,
  'Nhân viên vận hành máy móc': <Monitor />,
  'Chuyên viên quan hệ báo chí': <FileText />,
  'Tư vấn viên bán hàng': <ShoppingCart />,
  'Phát triển nội dung số': <Edit />,
  'Thuyền viên': <Anchor />,
  'Thợ làm móng': <Scissors />,
  'Phát triển phần mềm': <Code />,
  'Bác sĩ chuyên khoa (nội, ngoại, nhi...)': <User />,
  'Chuyên viên SEO/SEM': <Link />,
  'Nhân viên tổ chức sự kiện': <Calendar />,
  'Quản lý nhà thuốc': <ShoppingCart />,
  'Nhân viên điều phối sân bay': <Monitor />,
  'Chuyên viên sáng tạo nội dung': <Edit />,
  'Nhân viên lễ tân khách sạn': <User />,
  'Thiết kế giao diện đồ họa': <Monitor />,
  'Kỹ sư AI': <Cpu />,
  'Quản lý cơ sở y tế': <User />,
  'Giảng viên đại học': <User />,
  'Sáng tạo nội dung marketing': <Edit />,
  'Phiên dịch tiếng Hàn': <FileText />,
  'Chuyên viên phân tích đầu tư': <BarChart />,
  'Kỹ sư thiết kế hệ thống lạnh': <Monitor />,
  'Bán hàng thời trang nữ': <ShoppingCart />,
  'Đào tạo kỹ năng': <User />,
  'Chuyên viên thiết kế hệ thống tự động': <Cpu />,
  'Phát triển ứng dụng No-code': <Code />,
  'Kỹ sư hàng hải': <Anchor />,
  'Tiếp viên hàng không': <Monitor />,
  'Bán hàng công nghiệp': <ShoppingCart />,
  'Quản lý kho vận': <Box />,
  'Sản xuất cơ khí': <Monitor />,
  'Kiểm thử phần mềm': <HardDrive />,
  'Kiểm tra sản phẩm blockchain': <GitBranch />,
  'Nhân viên chăm sóc khách hàng': <User />,
  'Quản lý tài chính doanh nghiệp': <DollarSign />,
  'Kỹ sư điện': <Cpu />,
  'Quản lý dự án thiết kế nội thất': <Briefcase />,
  'Quản lý sản phẩm tài chính công nghệ': <DollarSign />,
  'Thực tập sinh kinh doanh': <User />,
  'Phiên dịch viên hội nghị': <FileText />,
  'Quản lý khách sạn': <User />,
  'Chuyên viên phát triển thị trường': <Search />,
  'Thiết kế đồ họa': <Edit />,
  'Kỹ sư tự động hóa': <Cpu />,
  'Chuyên viên bảo mật hệ thống tài chính': <Shield />,
  'Quản lý hệ thống ISO': <FileCog />,
  'Giao dịch viên ngân hàng': <DollarSign />,
  'Chăm sóc khách hàng': <User />,
  'Nhân viên lắp đặt hệ thống nhiệt lạnh': <User />,
  'Chuyên viên thẩm định bảo hiểm': <ShieldCheck />,
  'Quản lý chiến dịch quảng cáo': <Calendar />,
  'Kỹ sư bảo dưỡng thiết bị': <HardDrive />,
  'Quản lý đơn hàng TMĐT': <Box />,
  'Quản lý đội kinh doanh bảo hiểm': <DollarSign />,
  'Quản trị nhân sự': <User />,
  'Chuyên viên quản trị mạng': <Cloud />,
  'Kiểm soát chất lượng': <BarChart />,
  'Quản lý vận hành nhà hàng': <Briefcase />,
  'Nhân viên hỗ trợ sau bán hàng': <User />,
  'Chuyên viên đặt vé và tour': <Calendar />,
  'Kỹ sư xây dựng': <User />,
  'Nhân viên chăm sóc tại nhà': <User />,
  'Quản lý gian hàng TMĐT': <ShoppingCart />,
  'Chuyên viên logistics': <Truck />,
  'Nhân viên lập kế hoạch marketing': <FileCog />,
  'Nhân viên điều phối cảng': <MapPin />,
  'Phát triển website': <Code />,
  'Nhân viên vẽ kỹ thuật 2D/3D': <FilePlus />,
  'Chuyên viên điều phối chuỗi cung ứng': <Truck />,
  'Đào tạo ngoại ngữ': <User />,
  'Nhân viên kinh doanh phòng gym': <User />,
  'Quản lý chuỗi cung ứng': <Truck />,
  'Quản lý spa': <User />,
  'Kỹ thuật viên sản xuất da giày': <Scissors />,
  'Quản lý vận chuyển': <Truck />,
  'Phát triển ứng dụng di động': <Code />,
  'Phát triển ứng dụng': <Code />,
  'Quản lý văn phòng': <Briefcase />,
  'Bác sĩ chẩn đoán hình ảnh': <User />,
  'Chuyên viên điều phối giao nhận': <Truck />,
  'Nhân viên giám sát thi công': <User />,
  'Nhân viên bán hàng kỹ thuật': <Briefcase />,
  'Chuyên viên khoa học dữ liệu': <Database />,
  'Nhà phân tích Business Intelligence': <Search />,
  'Lập trình viên phần mềm': <Code />,
  'Quản lý dự án AI': <Cpu />,
  'Quản lý nhân sự': <User />,
  'Tổ chức đào tạo hướng nghiệp': <User />,
  'Quản lý hệ thống IT': <Cloud />,
  'Đảm bảo chất lượng sản xuất': <BarChart />,
  'Chuyên viên tư vấn giải pháp kỹ thuật': <Briefcase />,
  'Nhân viên kinh doanh online': <ShoppingCart />,
  'Thợ lắp ráp điện tử': <User />
};
